
export const counties = [
    {name: 'Adair', value: 'Adair'},
    {name: 'Andrew', value: 'Andrew'},
    {name: 'Atchison', value: 'Atchison'},
    {name: 'Audrain', value: 'Audrain'},
    {name: 'Barry', value: 'Barry'},
    {name: 'Barton', value: 'Barton'},
    {name: 'Bates', value: 'Bates'},
    {name: 'Benton', value: 'Benton'},
    {name: 'Bollinger', value: 'Bollinger'},
    {name: 'Boone', value: 'Boone'},
    {name: 'Buchanan', value: 'Buchanan'},
    {name: 'Butler', value: 'Butler'},
    {name: 'Caldwell', value: 'Caldwell'},
    {name: 'Callaway', value: 'Callaway'},
    {name: 'Camden', value: 'Camden'},
    {name: 'Cape Girardeau', value: 'Cape Girardeau'},
    {name: 'Carroll', value: 'Carroll'},
    {name: 'Carter', value: 'Carter'},
    {name: 'Cass', value: 'Cass'},
    {name: 'Cedar', value: 'Cedar'},
    {name: 'Chariton', value: 'Chariton'},
    {name: 'Christian', value: 'Christian'},
    {name: 'Clark', value: 'Clark'},
    {name: 'Clay', value: 'Clay'},
    {name: 'Clinton', value: 'Clinton'},
    {name: 'Cole', value: 'Cole'},
    {name: 'Cooper', value: 'Cooper'},
    {name: 'Crawford', value: 'Crawford'},
    {name: 'Dade', value: 'Dade'},
    {name: 'Dallas', value: 'Dallas'},
    {name: 'Daviess', value: 'Daviess'},
    {name: 'DeKalb', value: 'DeKalb'},
    {name: 'Dent', value: 'Dent'},
    {name: 'Douglas', value: 'Douglas'},
    {name: 'Dunklin', value: 'Dunklin'},
    {name: 'Franklin', value: 'Franklin'},
    {name: 'Gasconade', value: 'Gasconade'},
    {name: 'Gentry', value: 'Gentry'},
    {name: 'Greene', value: 'Greene'},
    {name: 'Grundy', value: 'Grundy'},
    {name: 'Harrison', value: 'Harrison'},
    {name: 'Henry', value: 'Henry'},
    {name: 'Hickory', value: 'Hickory'},
    {name: 'Holt', value: 'Holt'},
    {name: 'Howard', value: 'Howard'},
    {name: 'Howell', value: 'Howell'},
    {name: 'Iron', value: 'Iron'},
    {name: 'Jackson', value: 'Jackson'},
    {name: 'Jasper', value: 'Jasper'},
    {name: 'Jefferson', value: 'Jefferson'},
    {name: 'Johnson', value: 'Johnson'},
    {name: 'Knox', value: 'Knox'},
    {name: 'Laclede', value: 'Laclede'},
    {name: 'Lafayette', value: 'Lafayette'},
    {name: 'Lawrence', value: 'Lawrence'},
    {name: 'Lewis', value: 'Lewis'},
    {name: 'Lincoln', value: 'Lincoln'},
    {name: 'Linn', value: 'Linn'},
    {name: 'Livingston', value: 'Livingston'},
    {name: 'Macon', value: 'Macon'},
    {name: 'Madison', value: 'Madison'},
    {name: 'Maries', value: 'Maries'},
    {name: 'Marion', value: 'Marion'},
    {name: 'McDonald', value: 'McDonald'},
    {name: 'Mercer', value: 'Mercer'},
    {name: 'Miller', value: 'Miller'},
    {name: 'Mississippi', value: 'Mississippi'},
    {name: 'Moniteau', value: 'Moniteau'},
    {name: 'Monroe', value: 'Monroe'},
    {name: 'Montgomery', value: 'Montgomery'},
    {name: 'Morgan', value: 'Morgan'},
    {name: 'New Madrid', value: 'New Madrid'},
    {name: 'Newton', value: 'Newton'},
    {name: 'Nodaway', value: 'Nodaway'},
    {name: 'Oregon', value: 'Oregon'},
    {name: 'Osage', value: 'Osage'},
    {name: 'Ozark', value: 'Ozark'},
    {name: 'Pemiscot', value: 'Pemiscot'},
    {name: 'Perry', value: 'Perry'},
    {name: 'Pettis', value: 'Pettis'},
    {name: 'Phelps', value: 'Phelps'},
    {name: 'Pike', value: 'Pike'},
    {name: 'Platte', value: 'Platte'},
    {name: 'Polk', value: 'Polk'},
    {name: 'Pulaski', value: 'Pulaski'},
    {name: 'Putnam', value: 'Putnam'},
    {name: 'Ralls', value: 'Ralls'},
    {name: 'Randolph', value: 'Randolph'},
    {name: 'Ray', value: 'Ray'},
    {name: 'Reynolds', value: 'Reynolds'},
    {name: 'Ripley', value: 'Ripley'},
    {name: 'Saint Charles', value: 'St. Charles'},
    {name: 'Saint Clair', value: 'St. Clair'},
    {name: 'Saint Francois', value: 'St. Francois'},
    {name: 'Saint Louis', value: 'St. Louis'},
    {name: 'Saint Louis City', value: 'St. Louis City'},
    {name: 'Sainte Genevieve', value: 'Ste. Genevieve'},
    {name: 'Saline', value: 'Saline'},
    {name: 'Schuyler', value: 'Schuyler'},
    {name: 'Scotland', value: 'Scotland'},
    {name: 'Scott', value: 'Scott'},
    {name: 'Shannon', value: 'Shannon'},
    {name: 'Shelby', value: 'Shelby'},
    {name: 'Stoddard', value: 'Stoddard'},
    {name: 'Stone', value: 'Stone'},
    {name: 'Sullivan', value: 'Sullivan'},
    {name: 'Taney', value: 'Taney'},
    {name: 'Texas', value: 'Texas'},
    {name: 'Vernon', value: 'Vernon'},
    {name: 'Warren', value: 'Warren'},
    {name: 'Washington', value: 'Washington'},
    {name: 'Wayne', value: 'Wayne'},
    {name: 'Webster', value: 'Webster'},
    {name: 'Worth', value: 'Worth'},
    {name: 'Wright', value: 'Wright'}
];

export const probeCounties = [
    { name: 'St. Clair', value: 'St. Clair' },
    { name: 'Cape Girardeau', value: 'Cape Girardeau' },
    { name: 'Saline', value: 'Saline' },
    { name: 'Camden', value: 'Camden' },
    { name: 'Knox', value: 'Knox' },
    { name: 'Marion', value: 'Marion' },
    { name: 'Clark', value: 'Clark' },
    { name: 'Jasper', value: 'Jasper' },
    { name: 'Oregon', value: 'Oregon' },
    { name: 'Holt', value: 'Holt' },
    { name: 'Stone', value: 'Stone' },
    { name: 'Shelby', value: 'Shelby' },
    { name: 'St. Louis City', value: 'St. Louis City' },
    { name: 'Howard', value: 'Howard' },
    { name: 'St. Charles', value: 'St. Charles' },
    { name: 'Dallas', value: 'Dallas' },
    { name: 'Crawford', value: 'Crawford' },
    { name: 'Andrew', value: 'Andrew' },
    { name: 'Benton', value: 'Benton' },
    { name: 'Adair', value: 'Adair' },
    { name: 'Pike', value: 'Pike' },
    { name: 'Vernon', value: 'Vernon' },
    { name: 'Linn', value: 'Linn' },
    { name: 'Phelps', value: 'Phelps' },
    { name: 'St. Francois', value: 'St. Francois' },
    { name: 'Stoddard', value: 'Stoddard' },
    { name: 'Gentry', value: 'Gentry' },
    { name: 'St. Clair', value: 'St. Clair' },
    { name: 'Callaway', value: 'Callaway' },
    { name: 'Wayne', value: 'Wayne' },
    { name: 'Ripley', value: 'Ripley' },
    { name: 'Cass', value: 'Cass' },
    { name: 'Cooper', value: 'Cooper' },
    { name: 'Macon', value: 'Macon' },
    { name: 'Dunklin', value: 'Dunklin' },
    { name: 'St. Charles', value: 'St. Charles' },
    { name: 'Dent', value: 'Dent' },
    { name: 'Ste. Genevieve', value: 'Ste. Genevieve' },
    { name: 'Shannon', value: 'Shannon' },
    { name: 'St. Francois', value: 'St. Francois' },
    { name: 'Laclede', value: 'Laclede' },
    { name: 'Mississippi', value: 'Mississippi' },
    { name: 'Schuyler', value: 'Schuyler' },
    { name: 'Ste. Genevieve', value: 'Ste. Genevieve' },
    { name: 'Perry', value: 'Perry' },
    { name: 'Carter', value: 'Carter' },
    { name: 'Gasconade', value: 'Gasconade' },
    { name: 'Christian', value: 'Christian' },
    { name: 'Texas', value: 'Texas' },
    { name: 'Harrison', value: 'Harrison' },
    { name: 'Clay', value: 'Clay' },
    { name: 'Monroe', value: 'Monroe' },
    { name: 'Jackson', value: 'Jackson' },
    { name: 'Boone', value: 'Boone' },
    { name: 'Henry', value: 'Henry' },
    { name: 'Scotland', value: 'Scotland' },
    { name: 'Cole', value: 'Cole' },
    { name: 'Daviess', value: 'Daviess' },
    { name: 'Moniteau', value: 'Moniteau' },
    { name: 'Cedar', value: 'Cedar' },
    { name: 'Livingston', value: 'Livingston' },
    { name: 'Morgan', value: 'Morgan' },
    { name: 'Dade', value: 'Dade' },
    { name: 'Lafayette', value: 'Lafayette' },
    { name: 'Johnson', value: 'Johnson' },
    { name: 'Lewis', value: 'Lewis' },
    { name: 'Barton', value: 'Barton' },
    { name: 'Atchison', value: 'Atchison' },
    { name: 'Franklin', value: 'Franklin' },
    { name: 'Butler', value: 'Butler' },
    { name: 'Iron', value: 'Iron' },
    { name: 'Barry', value: 'Barry' },
    { name: 'Ozark', value: 'Ozark' },
    { name: 'St. Louis City', value: 'St. Louis City' },
    { name: 'Worth', value: 'Worth' },
    { name: 'Bates', value: 'Bates' },
    { name: 'Scott', value: 'Scott' },
    { name: 'Hickory', value: 'Hickory' },
    { name: 'Lincoln', value: 'Lincoln' },
    { name: 'Mercer', value: 'Mercer' },
    { name: 'Ralls', value: 'Ralls' },
    { name: 'Wright', value: 'Wright' },
    { name: 'Howell', value: 'Howell' },
    { name: 'Bollinger', value: 'Bollinger' },
    { name: 'Montgomery', value: 'Montgomery' },
    { name: 'Maries', value: 'Maries' },
    { name: 'Chariton', value: 'Chariton' },
    { name: 'Reynolds', value: 'Reynolds' },
    { name: 'Grundy', value: 'Grundy' },
    { name: 'St Louis', value: 'St. Louis' },
    { name: 'Taney', value: 'Taney' },
    { name: 'Randolph', value: 'Randolph' },
    { name: 'Pulaski', value: 'Pulaski' },
    { name: 'Webster', value: 'Webster' },
    { name: 'Lawrence', value: 'Lawrence' },
    { name: 'Polk', value: 'Polk' },
    { name: 'New Madrid', value: 'New Madrid' },
    { name: 'Pettis', value: 'Pettis' },
    { name: 'Ray', value: 'Ray' },
    { name: 'McDonald', value: 'McDonald' },
    { name: 'St. Louis', value: 'St. Louis' },
    { name: 'Pemiscot', value: 'Pemiscot' },
    { name: 'Miller', value: 'Miller' },
    { name: 'Greene', value: 'Greene' },
    { name: 'Washington', value: 'Washington' },
    { name: 'Carroll', value: 'Carroll' },
    { name: 'Platte', value: 'Platte' },
    { name: 'Warren', value: 'Warren' },
    { name: 'Putnam', value: 'Putnam' },
    { name: 'Buchanan', value: 'Buchanan' },
    { name: 'Caldwell', value: 'Caldwell' },
    { name: 'Newton', value: 'Newton' },
    { name: 'Osage', value: 'Osage' },
    { name: 'Madison', value: 'Madison' },
    { name: 'Audrain', value: 'Audrain' },
    { name: 'Clinton', value: 'Clinton' },
    { name: 'Dekalb', value: 'Dekalb' },
    { name: 'Jefferson', value: 'Jefferson' },
    { name: 'Nodaway', value: 'Nodaway' },
    { name: 'Sullivan', value: 'Sullivan' },
    { name: 'Douglas', value: 'Douglas' },
];


export const wazeIncidentsCounties = [
    { name: 'Polk', value: 'Polk' },
    { name: 'Cedar', value: 'Cedar' },
    { name: 'Osage', value: 'Osage' },
    { name: 'Jasper', value: 'Jasper' },
    { name: 'Henry', value: 'Henry' },
    { name: 'Howard', value: 'Howard' },
    { name: 'Oregon', value: 'Oregon' },
    { name: 'Dent', value: 'Dent' },
    { name: 'Pike', value: 'Pike' },
    { name: 'Pettis', value: 'Pettis' },
    { name: 'Carroll', value: 'Carroll' },
    { name: 'Johnson', value: 'Johnson' },
    { name: 'Wayne', value: 'Wayne' },
    { name: 'Ozark', value: 'Ozark' },
    { name: 'Knox', value: 'Knox' },
    { name: 'St Louis City', value: 'St. Louis City' },
    { name: 'Iron', value: 'Iron' },
    { name: 'Jackson', value: 'Jackson' },
    { name: 'Crawford', value: 'Crawford' },
    { name: 'Hickory', value: 'Hickory' },
    { name: 'Pulaski', value: 'Pulaski' },
    { name: 'Clark', value: 'Clark' },
    { name: 'Phelps', value: 'Phelps' },
    { name: 'Lewis', value: 'Lewis' },
    { name: 'Laclede', value: 'Laclede' },
    { name: 'Daviess', value: 'Daviess' },
    { name: 'Cooper', value: 'Cooper' },
    { name: 'Marion', value: 'Marion' },
    { name: 'DeKalb', value: 'DeKalb' },
    { name: 'Barry', value: 'Barry' },
    { name: 'Harrison', value: 'Harrison' },
    { name: 'Carter', value: 'Carter' },
    { name: 'Benton', value: 'Benton' },
    { name: 'Moniteau', value: 'Moniteau' },
    { name: 'St. Clair', value: 'St. Clair' },
    { name: 'Stoddard', value: 'Stoddard' },
    { name: 'Clinton', value: 'Clinton' },
    { name: 'Grundy', value: 'Grundy' },
    { name: 'Lincoln', value: 'Lincoln' },
    { name: 'Andrew', value: 'Andrew' },
    { name: 'Franklin', value: 'Franklin' },
    { name: 'Cape Girardeau', value: 'Cape Girardeau' },
    { name: 'Cole', value: 'Cole' },
    { name: 'Warren', value: 'Warren' },
    { name: 'Camden', value: 'Camden' },
    { name: 'Madison', value: 'Madison' },
    { name: 'Bollinger', value: 'Bollinger' },
    { name: 'Ralls', value: 'Ralls'},
    { name: 'Bates', value: 'Bates' },
    { name: 'Gentry', value: 'Gentry' },
    { name: 'McDonald', value: 'McDonald' },
    { name: 'Monroe', value: 'Monroe' },
    { name: 'Cass', value: 'Cass' },
    { name: 'Atchison', value: 'Atchison' },
    { name: 'Miller', value: 'Miller' },
    { name: 'Ripley', value: 'Ripley' },
    { name: 'Putnam', value: 'Putnam' },
    { name: 'St. Louis', value: 'St. Louis' },
    { name: 'St. Louis City', value: 'St. Louis City' },
    { name: 'St Louis', value: 'St. Louis' },
    { name: 'Jefferson', value: 'Jefferson' },
    { name: 'Platte', value: 'Platte' },
    { name: 'Sullivan', value: 'Sullivan' },
    { name: 'Chariton', value: 'Chariton' },
    { name: 'Nodaway', value: 'Nodaway' },
    { name: 'Perry', value: 'Perry' },
    { name: 'Scott', value: 'Scott' },
    { name: 'Ray', value: 'Ray' },
    { name: 'Randolph', value: 'Randolph' },
    { name: 'Butler', value: 'Butler' },
    { name: 'Callaway', value: 'Callaway' },
    { name: 'Holt', value: 'Holt' },
    { name: 'Macon', value: 'Macon' },
    { name: 'Reynolds', value: 'Reynolds' },
    { name: 'Dunklin', value: 'Dunklin' },
    { name: 'Barton', value: 'Barton' },
    { name: 'Taney', value: 'Taney' },
    { name: 'Mercer', value: 'Mercer' },
    { name: 'St. Francois', value: 'St. Francois' },
    { name: 'Ste. Genevieve', value: 'Ste. Genevieve' },
    { name: 'St Charles', value: 'St. Charles' },
    { name: 'Livingston', value: 'Livingston' },
    { name: 'Clay', value: 'Clay' },
    { name: 'Douglas', value: 'Douglas' },
    { name: 'Howell', value: 'Howell' },
    { name: 'St Francois', value: 'St. Francois' },
    { name: 'Linn', value: 'Linn' },
    { name: 'Adair', value: 'Adair' },
    { name: 'Audrain', value: 'Audrain' },
    { name: 'Dallas', value: 'Dallas' },
    { name: 'Lawrence', value: 'Lawrence' },
    { name: 'Ste Genevieve', value: 'Ste. Genevieve' },
    { name: 'Shannon', value: 'Shannon' },
    { name: 'Christian', value: 'Christian' },
    { name: 'Wright', value: 'Wright' },
    { name: 'Mississippi', value: 'Mississippi' },
    { name: 'Gasconade', value: 'Gasconade' },
    { name: 'Stone', value: 'Stone' },
    { name: 'Worth', value: 'Worth' },
    { name: 'St. Charles', value: 'St. Charles' },
    { name: 'Pemiscot', value: 'Pemiscot' },
    { name: 'Newton', value: 'Newton' },
    { name: 'Morgan', value: 'Morgan' },
    { name: 'St Clair', value: 'St. Clair' },
    { name: 'Greene', value: 'Greene' },
    { name: 'Shelby', value: 'Shelby' },
    { name: 'Boone', value: 'Boone' },
    { name: 'New Madrid', value: 'New Madrid' },
    { name: 'Buchanan', value: 'Buchanan' },
    { name: 'Lafayette', value: 'Lafayette' },
    { name: 'Washington', value: 'Washington' },
    { name: 'Webster', value: 'Webster' },
    { name: 'Dade', value: 'Dade' },
    { name: 'Vernon', value: 'Vernon' },
    { name: 'Saline', value: 'Saline' },
    { name: 'Montgomery', value: 'Montgomery' },
    { name: 'Caldwell', value: 'Caldwell' },
    { name: 'Texas', value: 'Texas' },
    { name: 'Schuyler', value: 'Schuyler' },
    { name: 'Scotland', value: 'Scotland' },
    { name: 'Maries', value: 'Maries' },
  ];

  

  export const wazeJamCounties = [
    { name: 'Hickory', value: 'Hickory' },
    { name: 'Barry', value: 'Barry' },
    { name: 'Carter', value: 'Carter' },
    { name: 'Maries', value: 'Maries' },
    { name: 'Howell', value: 'Howell' },
    { name: 'Ralls', value: 'Ralls' },
    { name: 'Jasper', value: 'Jasper' },
    { name: 'Randolph', value: 'Randolph' },
    { name: 'Daviess', value: 'Daviess' },
    { name: 'St Charles', value: 'St. Charles' },
    { name: 'Henry', value: 'Henry' },
    { name: 'Cole', value: 'Cole' },
    { name: 'Shelby', value: 'Shelby' },
    { name: 'Johnson', value: 'Johnson' },
    { name: 'Reynolds', value: 'Reynolds' },
    { name: 'Chariton', value: 'Chariton' },
    { name: 'Callaway', value: 'Callaway' },
    { name: 'New Madrid', value: 'New Madrid' },
    { name: 'Moniteau', value: 'Moniteau' },
    { name: 'Taney', value: 'Taney' },
    { name: 'Boone', value: 'Boone' },
    { name: 'Phelps', value: 'Phelps' },
    { name: 'Barton', value: 'Barton' },
    { name: 'Lafayette', value: 'Lafayette' },
    { name: 'Stone', value: 'Stone' },
    { name: 'Bollinger', value: 'Bollinger' },
    { name: 'Miller', value: 'Miller' },
    { name: 'Perry', value: 'Perry' },
    { name: 'Cedar', value: 'Cedar' },
    { name: 'Oregon', value: 'Oregon' },
    { name: 'Harrison', value: 'Harrison' },
    { name: 'Lawrence', value: 'Lawrence' },
    { name: 'Cooper', value: 'Cooper' },
    { name: 'Stoddard', value: 'Stoddard' },
    { name: 'St. Charles', value: 'St. Charles' },
    { name: 'Buchanan', value: 'Buchanan' },
    { name: 'Platte', value: 'Platte' },
    { name: 'Polk', value: 'Polk' },
    { name: 'Benton', value: 'Benton' },
    { name: 'Pike', value: 'Pike' },
    { name: 'Ozark', value: 'Ozark' },
    { name: 'Grundy', value: 'Grundy' },
    { name: 'Iron', value: 'Iron' },
    { name: 'Clay', value: 'Clay' },
    { name: 'Osage', value: 'Osage' },
    { name: 'Atchison', value: 'Atchison' },
    { name: 'Wayne', value: 'Wayne' },
    { name: 'Dunklin', value: 'Dunklin' },
    { name: 'Newton', value: 'Newton' },
    { name: 'Sullivan', value: 'Sullivan' },
    { name: 'Pulaski', value: 'Pulaski' },
    { name: 'Franklin', value: 'Franklin' },
    { name: 'Dent', value: 'Dent' },
    { name: 'Saline', value: 'Saline' },
    { name: 'Linn', value: 'Linn' },
    { name: 'Ripley', value: 'Ripley' },
    { name: 'Pettis', value: 'Pettis' },
    { name: 'Scotland', value: 'Scotland' },
    { name: 'St. Louis City', value: 'St. Louis City' },
    { name: 'St Louis City', value: 'St. Louis City' },
    { name: 'Jackson', value: 'Jackson' },
    { name: 'Scott', value: 'Scott' },
    { name: 'Douglas', value: 'Douglas' },
    { name: 'Crawford', value: 'Crawford' },
    { name: 'Nodaway', value: 'Nodaway' },
    { name: 'Monroe', value: 'Monroe' },
    { name: 'Clinton', value: 'Clinton' },
    { name: 'Ste Genevieve', value: 'Ste. Genevieve' },
    { name: 'Ray', value: 'Ray' },
    { name: 'Adair', value: 'Adair' },
    { name: 'St Louis', value: 'St. Louis' },
    { name: 'Lincoln', value: 'Lincoln' },
    { name: 'Dallas', value: 'Dallas' },
    { name: 'Webster', value: 'Webster' },
    { name: 'Schuyler', value: 'Schuyler' },
    { name: 'Camden', value: 'Camden' },
    { name: 'St. Louis', value: 'St. Louis' },
    { name: 'St. Francois', value: 'St. Francois' },
    { name: 'Jefferson', value: 'Jefferson' },
    { name: 'Montgomery', value: 'Montgomery' },
    { name: 'Laclede', value: 'Laclede' },
    { name: 'Wright', value: 'Wright' },
    { name: 'Texas', value: 'Texas' },
    { name: 'Greene', value: 'Greene' },
    { name: 'Vernon', value: 'Vernon' },
    { name: 'Washington', value: 'Washington' },
    { name: 'Macon', value: 'Macon' },
    { name: 'Warren', value: 'Warren' },
    { name: 'Butler', value: 'Butler' },
    { name: 'Marion', value: 'Marion' },
    { name: 'Audrain', value: 'Audrain' },
    { name: 'St Francois', value: 'St. Francois' },
    { name: 'Andrew', value: 'Andrew' },
    { name: 'Gentry', value: 'Gentry' },
    { name: 'Mississippi', value: 'Mississippi' },
    { name: 'Putnam', value: 'Putnam' },
    { name: 'Clark', value: 'Clark' },
    { name: 'St. Clair', value: 'St. Clair' },
    { name: 'Ste. Genevieve', value: 'Ste. Genevieve' },
    { name: 'Pemiscot', value: 'Pemiscot' },
    { name: 'Morgan', value: 'Morgan' },
    { name: 'St Clair', value: 'St. Clair' },
    { name: 'Cape Girardeau', value: 'Cape Girardeau' },
    { name: 'Livingston', value: 'Livingston' },
    { name: 'Holt', value: 'Holt' },
    { name: 'Shannon', value: 'Shannon' },
    { name: 'McDonald', value: 'McDonald' },
    { name: 'Caldwell', value: 'Caldwell' },
    { name: 'Mercer', value: 'Mercer' },
    { name: 'Worth', value: 'Worth' },
    { name: 'Christian', value: 'Christian' },
    { name: 'Cass', value: 'Cass' },
    { name: 'Gasconade', value: 'Gasconade' },
    { name: 'Carroll', value: 'Carroll' },
    { name: 'Howard', value: 'Howard' },
    { name: 'DeKalb', value: 'DeKalb' },
    { name: 'Madison', value: 'Madison' },
    { name: 'Dade', value: 'Dade' },
    { name: 'Bates', value: 'Bates' },
    { name: 'Lewis', value: 'Lewis' },
    { name: 'Knox', value: 'Knox' },
  ];

  export const detectorCounties = [
    { name: 'St. Louis City', value: 'St. Louis City' },
    { name: 'Franklin', value: 'Franklin' },
    { name: 'Lincoln', value: 'Lincoln' },
    { name: 'Jefferson', value: 'Jefferson' },
    { name: 'Mississippi', value: 'Mississippi' },
    { name: 'St. Louis', value: 'St. Louis' },
    { name: 'Warren', value: 'Warren' },
    { name: 'St Louis', value: 'St Louis' },
    { name: 'Cass', value: 'Cass' },
    { name: 'St Louis City', value: 'St. Louis City' },
    { name: 'Platte', value: 'Platte' },
    { name: 'Ray', value: 'Ray' },
    { name: 'St. Charles', value: 'St. Charles' },
    { name: 'Andrew', value: 'Andrew' },
    { name: 'Jackson', value: 'Jackson' },
    { name: 'St Charles', value: 'St. Charles' },
    { name: 'Clay', value: 'Clay' }
  ];
     
  
  

  