
export const counties = [
    {name: 'Adair', value: 'Adair'},
    {name: 'Andrew', value: 'Andrew'},
    {name: 'Atchison', value: 'Atchison'},
    {name: 'Audrain', value: 'Audrain'},
    {name: 'Barry', value: 'Barry'},
    {name: 'Barton', value: 'Barton'},
    {name: 'Bates', value: 'Bates'},
    {name: 'Benton', value: 'Benton'},
    {name: 'Bollinger', value: 'Bollinger'},
    {name: 'Boone', value: 'Boone'},
    {name: 'Buchanan', value: 'Buchanan'},
    {name: 'Butler', value: 'Butler'},
    {name: 'Caldwell', value: 'Caldwell'},
    {name: 'Callaway', value: 'Callaway'},
    {name: 'Camden', value: 'Camden'},
    {name: 'Cape Girardeau', value: 'Cape Girardeau'},
    {name: 'Carroll', value: 'Carroll'},
    {name: 'Carter', value: 'Carter'},
    {name: 'Cass', value: 'Cass'},
    {name: 'Cedar', value: 'Cedar'},
    {name: 'Chariton', value: 'Chariton'},
    {name: 'Christian', value: 'Christian'},
    {name: 'Clark', value: 'Clark'},
    {name: 'Clay', value: 'Clay'},
    {name: 'Clinton', value: 'Clinton'},
    {name: 'Cole', value: 'Cole'},
    {name: 'Cooper', value: 'Cooper'},
    {name: 'Crawford', value: 'Crawford'},
    {name: 'Dade', value: 'Dade'},
    {name: 'Dallas', value: 'Dallas'},
    {name: 'Daviess', value: 'Daviess'},
    {name: 'DeKalb', value: 'DeKalb'},
    {name: 'Dent', value: 'Dent'},
    {name: 'Douglas', value: 'Douglas'},
    {name: 'Dunklin', value: 'Dunklin'},
    {name: 'Franklin', value: 'Franklin'},
    {name: 'Gasconade', value: 'Gasconade'},
    {name: 'Gentry', value: 'Gentry'},
    {name: 'Greene', value: 'Greene'},
    {name: 'Grundy', value: 'Grundy'},
    {name: 'Harrison', value: 'Harrison'},
    {name: 'Henry', value: 'Henry'},
    {name: 'Hickory', value: 'Hickory'},
    {name: 'Holt', value: 'Holt'},
    {name: 'Howard', value: 'Howard'},
    {name: 'Howell', value: 'Howell'},
    {name: 'Iron', value: 'Iron'},
    {name: 'Jackson', value: 'Jackson'},
    {name: 'Jasper', value: 'Jasper'},
    {name: 'Jefferson', value: 'Jefferson'},
    {name: 'Johnson', value: 'Johnson'},
    {name: 'Knox', value: 'Knox'},
    {name: 'Laclede', value: 'Laclede'},
    {name: 'Lafayette', value: 'Lafayette'},
    {name: 'Lawrence', value: 'Lawrence'},
    {name: 'Lewis', value: 'Lewis'},
    {name: 'Lincoln', value: 'Lincoln'},
    {name: 'Linn', value: 'Linn'},
    {name: 'Livingston', value: 'Livingston'},
    {name: 'Macon', value: 'Macon'},
    {name: 'Madison', value: 'Madison'},
    {name: 'Maries', value: 'Maries'},
    {name: 'Marion', value: 'Marion'},
    {name: 'McDonald', value: 'McDonald'},
    {name: 'Mercer', value: 'Mercer'},
    {name: 'Miller', value: 'Miller'},
    {name: 'Mississippi', value: 'Mississippi'},
    {name: 'Moniteau', value: 'Moniteau'},
    {name: 'Monroe', value: 'Monroe'},
    {name: 'Montgomery', value: 'Montgomery'},
    {name: 'Morgan', value: 'Morgan'},
    {name: 'New Madrid', value: 'New Madrid'},
    {name: 'Newton', value: 'Newton'},
    {name: 'Nodaway', value: 'Nodaway'},
    {name: 'Oregon', value: 'Oregon'},
    {name: 'Osage', value: 'Osage'},
    {name: 'Ozark', value: 'Ozark'},
    {name: 'Pemiscot', value: 'Pemiscot'},
    {name: 'Perry', value: 'Perry'},
    {name: 'Pettis', value: 'Pettis'},
    {name: 'Phelps', value: 'Phelps'},
    {name: 'Pike', value: 'Pike'},
    {name: 'Platte', value: 'Platte'},
    {name: 'Polk', value: 'Polk'},
    {name: 'Pulaski', value: 'Pulaski'},
    {name: 'Putnam', value: 'Putnam'},
    {name: 'Ralls', value: 'Ralls'},
    {name: 'Randolph', value: 'Randolph'},
    {name: 'Ray', value: 'Ray'},
    {name: 'Reynolds', value: 'Reynolds'},
    {name: 'Ripley', value: 'Ripley'},
    {name: 'Saint Charles', value: 'St. Charles'},
    {name: 'Saint Clair', value: 'St. Clair'},
    {name: 'Saint Francois', value: 'St. Francois'},
    {name: 'Saint Louis', value: 'St. Louis'},
    {name: 'Saint Louis City', value: 'St. Louis City'},
    {name: 'Sainte Genevieve', value: 'Ste. Genevieve'},
    {name: 'Saline', value: 'Saline'},
    {name: 'Schuyler', value: 'Schuyler'},
    {name: 'Scotland', value: 'Scotland'},
    {name: 'Scott', value: 'Scott'},
    {name: 'Shannon', value: 'Shannon'},
    {name: 'Shelby', value: 'Shelby'},
    {name: 'Stoddard', value: 'Stoddard'},
    {name: 'Stone', value: 'Stone'},
    {name: 'Sullivan', value: 'Sullivan'},
    {name: 'Taney', value: 'Taney'},
    {name: 'Texas', value: 'Texas'},
    {name: 'Vernon', value: 'Vernon'},
    {name: 'Warren', value: 'Warren'},
    {name: 'Washington', value: 'Washington'},
    {name: 'Wayne', value: 'Wayne'},
    {name: 'Webster', value: 'Webster'},
    {name: 'Worth', value: 'Worth'},
    {name: 'Wright', value: 'Wright'}
];
